name: Deploy to Production

on:
  push:
    branches: [oned]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 89.116.23.50
          username: root
          password: ${{ secrets.VPS_PASSWORD }}
          script: /root/deploy.sh
